//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netas.Nipps.SystemManager.Presentation.Languages.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Service.
        /// </summary>
        public static string AddNewService {
            get {
                return ResourceManager.GetString("AddNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete the Admin.
        /// </summary>
        public static string AdminCanNotDeletedException {
            get {
                return ResourceManager.GetString("AdminCanNotDeletedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Alarms.
        /// </summary>
        public static string AlarmReset {
            get {
                return ResourceManager.GetString("AlarmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Pool Name.
        /// </summary>
        public static string ApplicationPoolName {
            get {
                return ResourceManager.GetString("ApplicationPoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Maintenance - Backup.
        /// </summary>
        public static string BackupTitle {
            get {
                return ResourceManager.GetString("BackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Backup.
        /// </summary>
        public static string ConfigBackup {
            get {
                return ResourceManager.GetString("ConfigBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Restore.
        /// </summary>
        public static string ConfigRestore {
            get {
                return ResourceManager.GetString("ConfigRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy.
        /// </summary>
        public static string Deploy {
            get {
                return ResourceManager.GetString("Deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Maintenance - Deploy.
        /// </summary>
        public static string DeployTitle {
            get {
                return ResourceManager.GetString("DeployTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string EmptyTable {
            get {
                return ResourceManager.GetString("EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand / Collapse.
        /// </summary>
        public static string ExpandCollapse {
            get {
                return ResourceManager.GetString("ExpandCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Date.
        /// </summary>
        public static string FinishDate {
            get {
                return ResourceManager.GetString("FinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name.
        /// </summary>
        public static string HostName {
            get {
                return ResourceManager.GetString("HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtered from _MAX_ records).
        /// </summary>
        public static string InfoFiltered {
            get {
                return ResourceManager.GetString("InfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued By.
        /// </summary>
        public static string IssuedBy {
            get {
                return ResourceManager.GetString("IssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _MENU_ records.
        /// </summary>
        public static string LengthMenu {
            get {
                return ResourceManager.GetString("LengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add License.
        /// </summary>
        public static string LicenseAdd {
            get {
                return ResourceManager.GetString("LicenseAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System License - Add License.
        /// </summary>
        public static string LicenseAddTitle {
            get {
                return ResourceManager.GetString("LicenseAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed To.
        /// </summary>
        public static string LicensedTo {
            get {
                return ResourceManager.GetString("LicensedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select License File.
        /// </summary>
        public static string LicenseFileSelect {
            get {
                return ResourceManager.GetString("LicenseFileSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load License.
        /// </summary>
        public static string LoadLicense {
            get {
                return ResourceManager.GetString("LoadLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Above Size.
        /// </summary>
        public static string LogArchiveAboveSize {
            get {
                return ResourceManager.GetString("LogArchiveAboveSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Every.
        /// </summary>
        public static string LogArchiveEvery {
            get {
                return ResourceManager.GetString("LogArchiveEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Logs.
        /// </summary>
        public static string LogDownload {
            get {
                return ResourceManager.GetString("LogDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download All Logs.
        /// </summary>
        public static string LogDownloadAll {
            get {
                return ResourceManager.GetString("LogDownloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Status - Download All Logs.
        /// </summary>
        public static string LogDownloadAllTitle {
            get {
                return ResourceManager.GetString("LogDownloadAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Info.
        /// </summary>
        public static string LogInfo {
            get {
                return ResourceManager.GetString("LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level.
        /// </summary>
        public static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Log Level.
        /// </summary>
        public static string LogLevelChange {
            get {
                return ResourceManager.GetString("LogLevelChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Archive File.
        /// </summary>
        public static string LogMaxArchiveFile {
            get {
                return ResourceManager.GetString("LogMaxArchiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon.
        /// </summary>
        public static string Logon {
            get {
                return ResourceManager.GetString("Logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your user name and password.
        /// </summary>
        public static string LogonMessage {
            get {
                return ResourceManager.GetString("LogonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Log Parameters.
        /// </summary>
        public static string LogParametersChange {
            get {
                return ResourceManager.GetString("LogParametersChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Status - Change Log Parameters.
        /// </summary>
        public static string LogParametersChangeTitle {
            get {
                return ResourceManager.GetString("LogParametersChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Logs.
        /// </summary>
        public static string LogReset {
            get {
                return ResourceManager.GetString("LogReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Status - Reset Logs.
        /// </summary>
        public static string LogResetTitle {
            get {
                return ResourceManager.GetString("LogResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download All SM Logs.
        /// </summary>
        public static string LogSMDownloadAll {
            get {
                return ResourceManager.GetString("LogSMDownloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        public static string MenuMainPage {
            get {
                return ResourceManager.GetString("MenuMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIPPS Management.
        /// </summary>
        public static string MenuNippsManagement {
            get {
                return ResourceManager.GetString("MenuNippsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Metrics.
        /// </summary>
        public static string MenuOperationalMetrics {
            get {
                return ResourceManager.GetString("MenuOperationalMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System License.
        /// </summary>
        public static string MenuSystemLicense {
            get {
                return ResourceManager.GetString("MenuSystemLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Maintenance.
        /// </summary>
        public static string MenuSystemMaintenance {
            get {
                return ResourceManager.GetString("MenuSystemMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sytem Parameters.
        /// </summary>
        public static string MenuSystemParameters {
            get {
                return ResourceManager.GetString("MenuSystemParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Status.
        /// </summary>
        public static string MenuSystemStatus {
            get {
                return ResourceManager.GetString("MenuSystemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        public static string MenuSystemVersions {
            get {
                return ResourceManager.GetString("MenuSystemVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string MenuUserManagement {
            get {
                return ResourceManager.GetString("MenuUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for change value.
        /// </summary>
        public static string MessageClickForChange {
            get {
                return ResourceManager.GetString("MessageClickForChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every application in this pool will restart, are you sure?.
        /// </summary>
        public static string MessageConfirmRestartPool {
            get {
                return ResourceManager.GetString("MessageConfirmRestartPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every application in this pool will stop, are you sure?.
        /// </summary>
        public static string MessageConfirmStopPool {
            get {
                return ResourceManager.GetString("MessageConfirmStopPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all logs between {0} and {1}.
        /// </summary>
        public static string MessageDownloadAllLogs {
            get {
                return ResourceManager.GetString("MessageDownloadAllLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is expired..
        /// </summary>
        public static string MessageExpiredPassword {
            get {
                return ResourceManager.GetString("MessageExpiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is failed..
        /// </summary>
        public static string MessageFail {
            get {
                return ResourceManager.GetString("MessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Host.
        /// </summary>
        public static string MessageHostSelect {
            get {
                return ResourceManager.GetString("MessageHostSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinishDate can not be less than StartDate or greater than Now .
        /// </summary>
        public static string MessageInvalidFinishDate {
            get {
                return ResourceManager.GetString("MessageInvalidFinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid..
        /// </summary>
        public static string MessageInvalidPassword {
            get {
                return ResourceManager.GetString("MessageInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password is entered..
        /// </summary>
        public static string MessageInvalidPasswordEntered {
            get {
                return ResourceManager.GetString("MessageInvalidPasswordEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is invalid..
        /// </summary>
        public static string MessageInvalidUsername {
            get {
                return ResourceManager.GetString("MessageInvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid values entered..
        /// </summary>
        public static string MessageInvalidValues {
            get {
                return ResourceManager.GetString("MessageInvalidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is done..
        /// </summary>
        public static string MessageOk {
            get {
                return ResourceManager.GetString("MessageOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is changed..
        /// </summary>
        public static string MessagePasswordChanged {
            get {
                return ResourceManager.GetString("MessagePasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Apllication Pool.
        /// </summary>
        public static string MessagePoolSelect {
            get {
                return ResourceManager.GetString("MessagePoolSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will remove, are you sure?.
        /// </summary>
        public static string MessageRemoveAppConfirm {
            get {
                return ResourceManager.GetString("MessageRemoveAppConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is created and sent via e-mail to the user..
        /// </summary>
        public static string MessageRenewPassword {
            get {
                return ResourceManager.GetString("MessageRenewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Site.
        /// </summary>
        public static string MessageSiteSelect {
            get {
                return ResourceManager.GetString("MessageSiteSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.  Please check the system logs for more detail..
        /// </summary>
        public static string MessageUnknownError {
            get {
                return ResourceManager.GetString("MessageUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is partial done..
        /// </summary>
        public static string MessageWarn {
            get {
                return ResourceManager.GetString("MessageWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETAS - IP Phone Services System Manager.
        /// </summary>
        public static string NippsTitle {
            get {
                return ResourceManager.GetString("NippsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Parameter.
        /// </summary>
        public static string ParameterChange {
            get {
                return ResourceManager.GetString("ParameterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Parameters.
        /// </summary>
        public static string ParameterTitle {
            get {
                return ResourceManager.GetString("ParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten Password.
        /// </summary>
        public static string PasswordForgotten {
            get {
                return ResourceManager.GetString("PasswordForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send New Password.
        /// </summary>
        public static string PasswordRenew {
            get {
                return ResourceManager.GetString("PasswordRenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product List.
        /// </summary>
        public static string ProductList {
            get {
                return ResourceManager.GetString("ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle.
        /// </summary>
        public static string Recycle {
            get {
                return ResourceManager.GetString("Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Maintenance - Recycle.
        /// </summary>
        public static string RecycleTitle {
            get {
                return ResourceManager.GetString("RecycleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Maintenance - Restore.
        /// </summary>
        public static string RestoreTitle {
            get {
                return ResourceManager.GetString("RestoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item.
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Request Count.
        /// </summary>
        public static string TotalRequestCount {
            get {
                return ResourceManager.GetString("TotalRequestCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Unhandled Error Count.
        /// </summary>
        public static string TotalUnhandledErrorCount {
            get {
                return ResourceManager.GetString("TotalUnhandledErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undeploy.
        /// </summary>
        public static string Undeploy {
            get {
                return ResourceManager.GetString("Undeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Maintenance - Undeploy.
        /// </summary>
        public static string UndeployTitle {
            get {
                return ResourceManager.GetString("UndeployTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        public static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Maintenance - Upgrade.
        /// </summary>
        public static string UpgradeTitle {
            get {
                return ResourceManager.GetString("UpgradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string UserAdd {
            get {
                return ResourceManager.GetString("UserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management - Add User.
        /// </summary>
        public static string UserAddTitle {
            get {
                return ResourceManager.GetString("UserAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string UserEdit {
            get {
                return ResourceManager.GetString("UserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management - Edit User.
        /// </summary>
        public static string UserEditTitle {
            get {
                return ResourceManager.GetString("UserEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Remove.
        /// </summary>
        public static string UserRemove {
            get {
                return ResourceManager.GetString("UserRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management - User Remove.
        /// </summary>
        public static string UserRemoveTitle {
            get {
                return ResourceManager.GetString("UserRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value with a valid extension..
        /// </summary>
        public static string ValAccept {
            get {
                return ResourceManager.GetString("ValAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid credit card number..
        /// </summary>
        public static string ValCreditcard {
            get {
                return ResourceManager.GetString("ValCreditcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date..
        /// </summary>
        public static string ValDate {
            get {
                return ResourceManager.GetString("ValDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date (ISO)..
        /// </summary>
        public static string ValDateISO {
            get {
                return ResourceManager.GetString("ValDateISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only digits..
        /// </summary>
        public static string ValDigits {
            get {
                return ResourceManager.GetString("ValDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string ValEmail {
            get {
                return ResourceManager.GetString("ValEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the same value again..
        /// </summary>
        public static string ValEqualTo {
            get {
                return ResourceManager.GetString("ValEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value less than or equal to {0}..
        /// </summary>
        public static string ValMax {
            get {
                return ResourceManager.GetString("ValMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than {0} characters..
        /// </summary>
        public static string ValMaxLength {
            get {
                return ResourceManager.GetString("ValMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value greater than or equal to {0}..
        /// </summary>
        public static string ValMin {
            get {
                return ResourceManager.GetString("ValMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least {0} characters..
        /// </summary>
        public static string ValMinLength {
            get {
                return ResourceManager.GetString("ValMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number..
        /// </summary>
        public static string ValNumber {
            get {
                return ResourceManager.GetString("ValNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value between {0} and {1}..
        /// </summary>
        public static string ValRange {
            get {
                return ResourceManager.GetString("ValRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value between {0} and {1} characters long..
        /// </summary>
        public static string ValRangeLength {
            get {
                return ResourceManager.GetString("ValRangeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix this field..
        /// </summary>
        public static string ValRemote {
            get {
                return ResourceManager.GetString("ValRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string ValRequired {
            get {
                return ResourceManager.GetString("ValRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL..
        /// </summary>
        public static string ValUrl {
            get {
                return ResourceManager.GetString("ValUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a ZIP file to deploy .
        /// </summary>
        public static string ZipFileSelect {
            get {
                return ResourceManager.GetString("ZipFileSelect", resourceCulture);
            }
        }
    }
}
